config/routes.rb
Rails.application.routes.draw do

  resources :videos do
    resources :articles
  end
  get 'welcome/index'

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :video
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates_presence_of :artist, :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET videos/1/articles
  def index
    @articles = @video.articles
  end

  # GET videos/1/articles/1
  def show
    
  end

  # GET videos/1/articles/new
  def new
    @article = @video.articles.build
  end

  # GET videos/1/articles/1/edit
  def edit
  end

  # POST videos/1/articles
  def create
    @article = @video.articles.build(article_params)

    if @article.save
      redirect_to([@article.video, @article], notice: 'Article was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT videos/1/articles/1
  def update
    if @article.update_attributes(article_params)
      redirect_to([@article.video, @article], notice: 'Article was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE videos/1/articles/1
  def destroy
    @article.destroy

    redirect_to video_articles_url(@video)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articles
      @video = Video.find(params[:video_id])
    end

    def set_article
      @article = @video.articles.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @vid = Video.find(params[:id])
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    # I wrote the next 4 lines as an alternative to dependant: :destroy
    # @vid = Video.find(params[:id])
    # @vid.articles.each do |art|
    #   art.delete
    # end
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:artist, :song, :pic_url, :vid_url, :lyrics)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for([@article.video, @article]) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 style="color: white;">Edit your thoughts here: </h1>

<%= render 'form' %>

<%= link_to 'Show', [@article.video, @article], :style => 'color: white; font-style: italic;' %> |
<%= link_to 'See all comments', video_articles_path(@article.video), :style => 'color: white; font-style: italic;' %>

app/views/articles/index.html.erb
<h1 style="color: white;">Listing articles</h1>
<br>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<br>
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.body %></td>
    <td><%= link_to 'Show', [article.video, article], :style => "color: green;" %></td>
    <td><%= link_to 'Edit', edit_video_article_path(article.video, article), :style => "color: yellow;" %></td>
    <td><%= link_to 'Destroy', [article.video, article], :confirm => 'Are you sure? This is permanent!', :method => :delete, :style => "color: red;" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_video_article_path(params[:video_id]), :style => "color: white; font-style: italic;" %>

app/views/articles/new.html.erb
<h1 style="color: #FFF;">Write your name and thoughts here...</h1>

<%= render 'form' %>

<%= link_to 'See all thoughts or Edit/Delete comments', video_articles_path(@article.video), :style => "color: white; font-style: italic;" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Body:</b>
  <%= @article.body %>
</p>


<%= link_to 'Edit this', edit_video_article_path(@article.video, @article), :style => "color: white; font-style: italic;" %>
<br>
<%= link_to 'See all thoughts', video_articles_path(@article.video), :style => "color: white; font-style: italic;" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Justplay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

    <footer>
    <%= link_to 'Back to Videos', videos_path, :class => "backtovideos" %>
    </footer>

  </body>
</html>

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :song %>
    <%= f.text_field :song %>
  </div>

  <div class="field">
    <%= f.label :pic_url %>
    <%= f.text_field :pic_url %>
  </div>

  <div class="field">
    <%= f.label :vid_url %>
    <%= f.text_field :vid_url %>
  </div>

  <div class="field">
    <%= f.label :lyrics %>
    <%= f.check_box :lyrics %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1 style="color: white;">Edit Here</h1>

<%= render 'form', video: @video %>

<%= link_to 'Display', @video, :style => 'color: white; font-style: italic;' %>

app/views/videos/index.html.erb
<div class="videos-index-div">

<p id="notice"><%= notice %></p>

<h1 class="videos-index"><span class="h1-span">Just Click the Pics to </span>Watch or Sing?</h1>

<table>
  <thead>
    <tr>
      <th> ___List of Artists ___</th>
      <th> List of Songs ___</th>
      <th> Picture or Artist or Song</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.artist %></td>
        <td><%= video.song %></td>
        <td><a href="<%= video.vid_url %>"><img class="index-iframe" src="<%= video.pic_url %>" alt="<%= video.song %>"></a></td>

        <td class="index-info"><%= link_to 'Info', video, {:style => 'color: #0f0; text-decoration: none;'}%></td>
        <td class="index-edit"><%= link_to 'Edit', edit_video_path(video), {:style => 'color: #cc0; text-decoration: none;'}%></td>
        <td class="index-delete"><%= link_to 'Destroy', video, :style => 'color: #d00; text-decoration: none;', method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <td class="index-thoughts"><%= link_to 'Thoughts?', new_video_article_path(video), {:style => 'color: #FFF; text-decoration: none;'} %></td>
        <td><%= video.articles.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a New Video Here', new_video_path, {:style => 'color: #FF0; text-decoration: none; font-size: 36px; font-style: italic;'} %>

</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="transparent-show-div">

  <p style="font-size:30px">
    <%= @video.artist %>
  </p>

  <p style="font-size:24px">
    <%= @video.song %>
  </p>

  <p>
    <strong></strong>
    <a href="<%= @video.vid_url %>"><img class="show-image" src="<%= @video.pic_url %>" alt="<%= @video.song %>"></a>
  </p>

  <p>
    <strong>Click the Pic!</strong>
    <%= %>
  </p>

</div>

<!-- <p>
  <strong>Lyrics:</strong>
  <%= @video.lyrics %>
</p> -->

<div class="thoughts-div">
  <% @vid.articles.each do |art| %>
  <p><%= art.title%> - <%= art.body %></p>
  <br>
  <% end %>
</div>

<br>
<br>
<%= link_to 'Edit This Video', edit_video_path(@video), :style => 'color: white; font-style: italic;' %>

app/views/welcome/index.html.erb
<div class="welcome-div1">
  <h1 class="welcome-heading">Welcome to JustPlayIt!</h1>
  <br>
  <h3 class="welcome-rules">Please come in and let's sing by the fire...</h3>
</div >




<div class='image-div'>
  <img class='welcome-image' src="https://media.giphy.com/media/cNZkqYmPeea1a/source.gif" alt="sing by the fireplace">
  <!-- <%= image_tag("marley.gif", alt: "marley rockin") %> -->
</div>





<div class="welcome-div2">
  <br>
    <h4 class="welcome-play"><%= link_to 'Play' , videos_path, {:style => 'color: #ff7400; font-style: none;'} %></h4>
  <br>
</div>






















<p>Find me in app/views/welcome/index.html.erb</p>